# Generated by Django 4.1.7 on 2023-03-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_category_product_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='category_id',
        ),
    ]
